// @generated by xtask/shader-bindgen from Slang reflection JSON.
// DO NOT EDIT. Regenerate: cargo run -p xtask --bin shader-bindgen -- \
//   shaders/reflection crates/prism-render/src/shader_bindings.rs
#![allow(dead_code)]

pub mod bindless {
    //! Bindings reflected from shaders/slang/bindless.slang

    /// Entry point names (for VkPipelineShaderStageCreateInfo).
    pub const ENTRY_FRAGMENT_MAIN: &str = "fragmentMain"; // stage: FRAGMENT

    /// Push-constant block size in bytes (reflected).
    pub const PUSH_CONSTANT_SIZE: u32 = 96;

    // --- descriptor set 0 ---
    pub const FRAME_SET: u32 = 0;
    pub const FRAME_BINDING: u32 = 0; // UNIFORM_BUFFER

    // --- descriptor set 2 ---
    pub const BINDLESS_CUBES_SET: u32 = 2;
    pub const BINDLESS_CUBES_BINDING: u32 = 0; // COMBINED_IMAGE_SAMPLER
}

pub mod gizmo {
    //! Bindings reflected from shaders/slang/gizmo.slang

    /// Entry point names (for VkPipelineShaderStageCreateInfo).
    pub const ENTRY_VERTEX_MAIN: &str = "vertexMain"; // stage: VERTEX
    pub const ENTRY_FRAGMENT_MAIN: &str = "fragmentMain"; // stage: FRAGMENT

    /// Push-constant block size in bytes (reflected).
    pub const PUSH_CONSTANT_SIZE: u32 = 64;
}

pub mod mesh {
    //! Bindings reflected from shaders/slang/mesh.slang

    /// Entry point names (for VkPipelineShaderStageCreateInfo).
    pub const ENTRY_VERTEX_MAIN: &str = "vertexMain"; // stage: VERTEX
    pub const ENTRY_FRAGMENT_MAIN: &str = "fragmentMain"; // stage: FRAGMENT

    /// Push-constant block size in bytes (reflected).
    pub const PUSH_CONSTANT_SIZE: u32 = 64;

    // --- descriptor set 0 ---
    pub const FRAME_SET: u32 = 0;
    pub const FRAME_BINDING: u32 = 0; // UNIFORM_BUFFER
}

pub mod overlay {
    //! Bindings reflected from shaders/slang/overlay.slang

    /// Entry point names (for VkPipelineShaderStageCreateInfo).
    pub const ENTRY_VERTEX_MAIN: &str = "vertexMain"; // stage: VERTEX
    pub const ENTRY_FRAGMENT_MAIN: &str = "fragmentMain"; // stage: FRAGMENT

    // --- descriptor set 0 ---
    pub const FONT_TEX_SET: u32 = 0;
    pub const FONT_TEX_BINDING: u32 = 0; // COMBINED_IMAGE_SAMPLER
}

pub mod pbr {
    //! Bindings reflected from shaders/slang/pbr.slang

    /// Entry point names (for VkPipelineShaderStageCreateInfo).
    pub const ENTRY_FRAGMENT_MAIN: &str = "fragmentMain"; // stage: FRAGMENT

    /// Push-constant block size in bytes (reflected).
    pub const PUSH_CONSTANT_SIZE: u32 = 92;

    // --- descriptor set 0 ---
    pub const FRAME_SET: u32 = 0;
    pub const FRAME_BINDING: u32 = 0; // UNIFORM_BUFFER

    // --- descriptor set 1 ---
    pub const ENV_CUBE_SET: u32 = 1;
    pub const ENV_CUBE_BINDING: u32 = 0; // COMBINED_IMAGE_SAMPLER
}

pub mod shadow {
    //! Bindings reflected from shaders/slang/shadow.slang

    /// Entry point names (for VkPipelineShaderStageCreateInfo).
    pub const ENTRY_COMPUTE_MAIN: &str = "computeMain"; // stage: COMPUTE

    /// Push-constant block size in bytes (reflected).
    pub const PUSH_CONSTANT_SIZE: u32 = 48;

    // --- descriptor set 0 ---
    pub const FRAME_SET: u32 = 0;
    pub const FRAME_BINDING: u32 = 0; // UNIFORM_BUFFER
    pub const GBUFFER_A_SET: u32 = 0;
    pub const GBUFFER_A_BINDING: u32 = 1; // COMBINED_IMAGE_SAMPLER
    pub const GBUFFER_B_SET: u32 = 0;
    pub const GBUFFER_B_BINDING: u32 = 2; // COMBINED_IMAGE_SAMPLER
    pub const SHADOW_OUTPUT_SET: u32 = 0;
    pub const SHADOW_OUTPUT_BINDING: u32 = 3; // COMBINED_IMAGE_SAMPLER
    pub const TLAS_SET: u32 = 0;
    pub const TLAS_BINDING: u32 = 4; // UNIFORM_BUFFER
}
