// @generated by xtask/shader-bindgen from Slang reflection JSON.
// DO NOT EDIT. Regenerate: cargo run -p xtask --bin shader-bindgen -- \
//   shaders/reflection crates/prism-render/src/shader_bindings.rs
#![allow(dead_code, non_snake_case)]

pub mod gizmo {
    //! Bindings reflected from shaders/slang/gizmo.slang

    /// Entry point names (for VkPipelineShaderStageCreateInfo).
    pub const ENTRY_VERTEX_MAIN: &str = "vertexMain"; // stage: VERTEX
    pub const ENTRY_FRAGMENT_MAIN: &str = "fragmentMain"; // stage: FRAGMENT

    /// Push-constant block size in bytes (reflected).
    pub const PUSH_CONSTANT_SIZE: u32 = 0;

    /// Push-constant struct (auto-generated from Slang `GizmoPush`).
    #[repr(C)]
    #[derive(Clone, Copy, Default)]
    pub struct GizmoPush {
        /// offset 0, size 64
        pub viewProj: [[f32; 4]; 4],
    }
}

pub mod gtao {
    //! Bindings reflected from shaders/slang/gtao.slang

    /// Entry point names (for VkPipelineShaderStageCreateInfo).
    pub const ENTRY_VERTEX_MAIN: &str = "vertexMain"; // stage: VERTEX
    pub const ENTRY_FRAGMENT_MAIN: &str = "fragmentMain"; // stage: FRAGMENT

    /// Push-constant block size in bytes (reflected).
    pub const PUSH_CONSTANT_SIZE: u32 = 0;

    // --- descriptor set 0 ---
    pub const DEPTH_TEX_SET: u32 = 0;
    pub const DEPTH_TEX_BINDING: u32 = 0; // COMBINED_IMAGE_SAMPLER
    pub const DEPTH_SAMPLER_SET: u32 = 0;
    pub const DEPTH_SAMPLER_BINDING: u32 = 1; // COMBINED_IMAGE_SAMPLER

    // --- descriptor set 1 ---
    pub const NORMAL_TEX_SET: u32 = 1;
    pub const NORMAL_TEX_BINDING: u32 = 0; // COMBINED_IMAGE_SAMPLER
    pub const NORMAL_SAMPLER_SET: u32 = 1;
    pub const NORMAL_SAMPLER_BINDING: u32 = 1; // COMBINED_IMAGE_SAMPLER

    /// Push-constant struct (auto-generated from Slang `GtaoPush`).
    #[repr(C)]
    #[derive(Clone, Copy, Default)]
    pub struct GtaoPush {
        /// offset 0, size 64
        pub inv_proj: [[f32; 4]; 4],
        /// offset 64, size 8
        pub viewport: [f32; 2],
        /// offset 72, size 4
        pub radius: f32,
        /// offset 76, size 4
        pub mode: u32,
        /// offset 80, size 4
        pub _pad0: u32,
    }
}

pub mod mesh_vert {
    //! Bindings reflected from shaders/slang/mesh_vert.slang

    /// Entry point names (for VkPipelineShaderStageCreateInfo).
    pub const ENTRY_VERTEX_MAIN: &str = "vertexMain"; // stage: VERTEX

    /// Push-constant block size in bytes (reflected).
    pub const PUSH_CONSTANT_SIZE: u32 = 0;

    // --- descriptor set 0 ---
    pub const FRAME_SET: u32 = 0;
    pub const FRAME_BINDING: u32 = 0; // UNIFORM_BUFFER

    /// Push-constant struct (auto-generated from Slang `MeshPush`).
    #[repr(C)]
    #[derive(Clone, Copy, Default)]
    pub struct MeshPush {
        /// offset 0, size 64
        pub model: [[f32; 4]; 4],
    }
}

pub mod post {
    //! Bindings reflected from shaders/slang/post.slang

    /// Entry point names (for VkPipelineShaderStageCreateInfo).
    pub const ENTRY_VERTEX_MAIN: &str = "vertexMain"; // stage: VERTEX
    pub const ENTRY_FRAGMENT_MAIN: &str = "fragmentMain"; // stage: FRAGMENT

    /// Push-constant block size in bytes (reflected).
    pub const PUSH_CONSTANT_SIZE: u32 = 0;

    // --- descriptor set 0 ---
    pub const HDR_TEX_SET: u32 = 0;
    pub const HDR_TEX_BINDING: u32 = 0; // COMBINED_IMAGE_SAMPLER

    /// Push-constant struct (auto-generated from Slang `PostPush`).
    #[repr(C)]
    #[derive(Clone, Copy, Default)]
    pub struct PostPush {
        /// offset 0, size 4
        pub tonemapMode: u32,
    }
}

pub mod pt_render {
    //! Bindings reflected from shaders/slang/pt_render.slang

    /// Entry point names (for VkPipelineShaderStageCreateInfo).
    pub const ENTRY_PT_MAIN: &str = "ptMain"; // stage: COMPUTE

    /// Push-constant block size in bytes (reflected).
    pub const PUSH_CONSTANT_SIZE: u32 = 0;

    // --- descriptor set 0 ---
    pub const ACCUM_IMAGE_SET: u32 = 0;
    pub const ACCUM_IMAGE_BINDING: u32 = 0; // COMBINED_IMAGE_SAMPLER
    pub const SAMPLE_COUNT_SET: u32 = 0;
    pub const SAMPLE_COUNT_BINDING: u32 = 1; // COMBINED_IMAGE_SAMPLER
    pub const TLAS_SET: u32 = 0;
    pub const TLAS_BINDING: u32 = 2; // UNIFORM_BUFFER
    pub const VERTEX_DATA_SET: u32 = 0;
    pub const VERTEX_DATA_BINDING: u32 = 3; // UNIFORM_BUFFER
    pub const INDICES_SET: u32 = 0;
    pub const INDICES_BINDING: u32 = 4; // UNIFORM_BUFFER
    pub const OUTPUT_IMAGE_SET: u32 = 0;
    pub const OUTPUT_IMAGE_BINDING: u32 = 5; // COMBINED_IMAGE_SAMPLER
    pub const INSTANCE_META_SET: u32 = 0;
    pub const INSTANCE_META_BINDING: u32 = 6; // UNIFORM_BUFFER
    pub const MATERIALS_SET: u32 = 0;
    pub const MATERIALS_BINDING: u32 = 7; // UNIFORM_BUFFER

    // --- descriptor set 1 ---
    pub const GLOBAL_SAMPLERS_SET: u32 = 1;
    pub const GLOBAL_SAMPLERS_BINDING: u32 = 0; // UNIFORM_BUFFER
    pub const BINDLESS_SRVS_SET: u32 = 1;
    pub const BINDLESS_SRVS_BINDING: u32 = 1; // UNIFORM_BUFFER

    // --- descriptor set 2 ---
    pub const ENV_CUBE_SET: u32 = 2;
    pub const ENV_CUBE_BINDING: u32 = 0; // COMBINED_IMAGE_SAMPLER

    /// Push-constant struct (auto-generated from Slang `PtPush`).
    #[repr(C)]
    #[derive(Clone, Copy, Default)]
    pub struct PtPush {
        /// offset 0, size 64
        pub inv_view_proj: [[f32; 4]; 4],
        /// offset 64, size 16
        pub camera_pos: [f32; 4],
        /// offset 80, size 16
        pub light_dir: [f32; 4],
        /// offset 96, size 16
        pub light_color: [f32; 4],
        /// offset 112, size 16
        pub params: [u32; 4],
        /// offset 128, size 4
        pub ray_max_distance: f32,
        /// offset 132, size 4
        pub max_iterations: u32,
    }
}

pub mod scene_frag {
    //! Bindings reflected from shaders/slang/scene_frag.slang

    /// Entry point names (for VkPipelineShaderStageCreateInfo).
    pub const ENTRY_FRAGMENT_MAIN: &str = "fragmentMain"; // stage: FRAGMENT

    /// Push-constant block size in bytes (reflected).
    pub const PUSH_CONSTANT_SIZE: u32 = 0;

    // --- descriptor set 0 ---
    pub const FRAME_SET: u32 = 0;
    pub const FRAME_BINDING: u32 = 0; // UNIFORM_BUFFER
    pub const MATERIALS_SET: u32 = 0;
    pub const MATERIALS_BINDING: u32 = 1; // UNIFORM_BUFFER
    pub const POINT_LIGHTS_SET: u32 = 0;
    pub const POINT_LIGHTS_BINDING: u32 = 2; // UNIFORM_BUFFER

    // --- descriptor set 1 ---
    pub const GLOBAL_SAMPLERS_SET: u32 = 1;
    pub const GLOBAL_SAMPLERS_BINDING: u32 = 0; // UNIFORM_BUFFER
    pub const BINDLESS_SRVS_SET: u32 = 1;
    pub const BINDLESS_SRVS_BINDING: u32 = 1; // UNIFORM_BUFFER

    // --- descriptor set 2 ---
    pub const ENV_CUBE_SET: u32 = 2;
    pub const ENV_CUBE_BINDING: u32 = 0; // COMBINED_IMAGE_SAMPLER
    pub const IRRADIANCE_CUBE_SET: u32 = 2;
    pub const IRRADIANCE_CUBE_BINDING: u32 = 1; // COMBINED_IMAGE_SAMPLER
    pub const PREFILTERED_CUBE_SET: u32 = 2;
    pub const PREFILTERED_CUBE_BINDING: u32 = 2; // COMBINED_IMAGE_SAMPLER

    // --- descriptor set 3 ---
    pub const SHADOW_MAP_SET: u32 = 3;
    pub const SHADOW_MAP_BINDING: u32 = 0; // COMBINED_IMAGE_SAMPLER
    pub const SHADOW_SAMPLER_SET: u32 = 3;
    pub const SHADOW_SAMPLER_BINDING: u32 = 1; // COMBINED_IMAGE_SAMPLER

    // --- descriptor set 4 ---
    pub const AO_TEX_SET: u32 = 4;
    pub const AO_TEX_BINDING: u32 = 0; // COMBINED_IMAGE_SAMPLER

    // --- descriptor set 5 ---
    pub const PROBE_VOLUME_SET: u32 = 5;
    pub const PROBE_VOLUME_BINDING: u32 = 0; // COMBINED_IMAGE_SAMPLER
    pub const PROBE_INFO_SET: u32 = 5;
    pub const PROBE_INFO_BINDING: u32 = 1; // UNIFORM_BUFFER

    /// Push-constant struct (auto-generated from Slang `PbrBindlessPush`).
    #[repr(C)]
    #[derive(Clone, Copy, Default)]
    pub struct PbrBindlessPush {
        /// offset 0, size 64
        pub model: [[f32; 4]; 4],
        /// offset 64, size 4
        pub material_slot: u32,
        /// offset 68, size 4
        pub env_handle: u32,
        /// offset 72, size 4
        pub albedo_idx: u32,
        /// offset 76, size 4
        pub normal_idx: u32,
        /// offset 80, size 4
        pub debug_flags: u32,
        /// offset 96, size 12
        pub _padding: [u32; 3],
    }
}

pub mod shadow_depth {
    //! Bindings reflected from shaders/slang/shadow_depth.slang

    /// Entry point names (for VkPipelineShaderStageCreateInfo).
    pub const ENTRY_VERTEX_MAIN: &str = "vertexMain"; // stage: VERTEX
    pub const ENTRY_FRAGMENT_MAIN: &str = "fragmentMain"; // stage: FRAGMENT

    /// Push-constant block size in bytes (reflected).
    pub const PUSH_CONSTANT_SIZE: u32 = 0;

    /// Push-constant struct (auto-generated from Slang `ShadowPush`).
    #[repr(C)]
    #[derive(Clone, Copy, Default)]
    pub struct ShadowPush {
        /// offset 0, size 64
        pub model: [[f32; 4]; 4],
        /// offset 64, size 64
        pub lightViewProj: [[f32; 4]; 4],
    }
}

pub mod skybox {
    //! Bindings reflected from shaders/slang/skybox.slang

    /// Entry point names (for VkPipelineShaderStageCreateInfo).
    pub const ENTRY_VERTEX_MAIN: &str = "vertexMain"; // stage: VERTEX
    pub const ENTRY_FRAGMENT_MAIN: &str = "fragmentMain"; // stage: FRAGMENT

    /// Push-constant block size in bytes (reflected).
    pub const PUSH_CONSTANT_SIZE: u32 = 0;

    // --- descriptor set 0 ---
    pub const ENV_CUBE_SET: u32 = 0;
    pub const ENV_CUBE_BINDING: u32 = 0; // COMBINED_IMAGE_SAMPLER

    /// Push-constant struct (auto-generated from Slang `SkyboxPush`).
    #[repr(C)]
    #[derive(Clone, Copy, Default)]
    pub struct SkyboxPush {
        /// offset 0, size 64
        pub invViewRot: [[f32; 4]; 4],
        /// offset 64, size 16
        pub _pad0: [f32; 4],
        /// offset 80, size 16
        pub _pad1: [f32; 4],
    }
}
