[package]
name = "prism-editor"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "egui editor UI for PrismaRev (inspector, debug, render settings, baking)"

[dependencies]
prism-ecs = { path = "../prism-ecs" }
prism-engine = { path = "../prism-engine" }
prism-render = { path = "../prism-render" }
glam.workspace = true
prism-asset = { path = "../prism-asset", features = ["core"] }
egui = { workspace = true }
anyhow = { workspace = true }
ash = { workspace = true }
inventory = "0.3"
