[package]
name = "asset-cooker"
version.workspace = true
edition = "2021"
license.workspace = true
description = "Cooker framework for the resource pipeline"

[dependencies]
asset-core = { path = "../asset-core" }
asset-db = { path = "../asset-db" }
asset-package = { path = "../asset-package" }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
tracing = "0.1"
anyhow = { workspace = true }
image = { workspace = true }
xxhash-rust = { version = "0.8", features = ["xxh3"] }
ctt = { workspace = true }

[dev-dependencies]
tempfile = "3"
