[package]
name = "prism-asset-package"
version.workspace = true
edition = "2021"
license.workspace = true
description = ".pak file format for the resource pipeline"

[dependencies]
prism-asset-core = { path = "../prism-asset-core" }
serde = { workspace = true }
xxhash-rust = { workspace = true }
zstd = { workspace = true }
thiserror = { workspace = true }
tracing = "0.1"
tokio = { workspace = true }

[dev-dependencies]
tempfile = "3"
