[package]
name = "prism-asset-cooker"
version.workspace = true
edition = "2021"
license.workspace = true
description = "Cooker framework for the resource pipeline"

[dependencies]
prism-asset-core = { path = "../prism-asset-core" }
prism-asset-db = { path = "../prism-asset-db" }
prism-asset-importer = { path = "../prism-asset-importer" }
prism-asset-package = { path = "../prism-asset-package" }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
tracing = "0.1"
anyhow = { workspace = true }
image = { workspace = true }
xxhash-rust = { version = "0.8", features = ["xxh3"] }
ctt = { workspace = true, optional = true }

[features]
default = ["texture-compression"]
texture-compression = ["dep:ctt"]

[dev-dependencies]
tempfile = "3"
