// @generated by xtask/shader-bindgen from Slang reflection.
// DO NOT EDIT. Regenerate: `cd xtask && cargo run --bin shader-bindgen -- \
//   ../shaders/reflection ../crates/prism-render/src/shader_bindings`

//! Bindings reflected from `shaders/slang/gtao.slang`.

#![allow(dead_code, non_snake_case)]


/// Entry point names (for VkPipelineShaderStageCreateInfo).
pub const ENTRY_VERTEX_MAIN: &str = "vertexMain"; // stage: VERTEX
pub const ENTRY_FRAGMENT_MAIN: &str = "fragmentMain"; // stage: FRAGMENT

/// Push-constant block size in bytes (reflected).
pub const PUSH_CONSTANT_SIZE: u32 = 0;

// --- descriptor set 0 ---
pub const DEPTH_TEX_SET: u32 = 0;
pub const DEPTH_TEX_BINDING: u32 = 0; // COMBINED_IMAGE_SAMPLER
pub const DEPTH_SAMPLER_SET: u32 = 0;
pub const DEPTH_SAMPLER_BINDING: u32 = 1; // COMBINED_IMAGE_SAMPLER

// --- descriptor set 1 ---
pub const NORMAL_TEX_SET: u32 = 1;
pub const NORMAL_TEX_BINDING: u32 = 0; // COMBINED_IMAGE_SAMPLER
pub const NORMAL_SAMPLER_SET: u32 = 1;
pub const NORMAL_SAMPLER_BINDING: u32 = 1; // COMBINED_IMAGE_SAMPLER

/// Push-constant struct (auto-generated from Slang `GtaoPush`).
#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct GtaoPush {
    /// offset 0, size 64
    pub inv_proj: [[f32; 4]; 4],
    /// offset 64, size 8
    pub viewport: [f32; 2],
    /// offset 72, size 4
    pub radius: f32,
    /// offset 76, size 4
    pub mode: u32,
    /// offset 80, size 4
    pub _pad0: u32,
}
