// @generated by xtask/shader-bindgen from Slang reflection.
// DO NOT EDIT. Regenerate: `cd xtask && cargo run --bin shader-bindgen -- \
//   ../shaders/reflection ../crates/prism-render/src/shader_bindings`

//! Bindings reflected from `shaders/slang/mesh_vert.slang`.

#![allow(dead_code, non_snake_case)]


/// Entry point names (for VkPipelineShaderStageCreateInfo).
pub const ENTRY_VERTEX_MAIN: &str = "vertexMain"; // stage: VERTEX

/// Push-constant block size in bytes (reflected).
pub const PUSH_CONSTANT_SIZE: u32 = 0;

// --- descriptor set 0 ---
pub const FRAME_SET: u32 = 0;
pub const FRAME_BINDING: u32 = 0; // UNIFORM_BUFFER

/// Push-constant struct (auto-generated from Slang `MeshPush`).
#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct MeshPush {
    /// offset 0, size 64
    pub model: [[f32; 4]; 4],
}
