// @generated by xtask/shader-bindgen from Slang reflection.
// DO NOT EDIT. Regenerate: `cd crates/xtask && cargo run --bin shader-bindgen -- \\
//   ../../assets/shaders/reflection ../../crates/prism-render/src/shader_bindings`
#![allow(dead_code, non_snake_case)]

pub mod gizmo;
pub mod gtao;
pub mod mesh_vert;
pub mod post;
pub mod pt_render;
pub mod scene_frag;
pub mod shadow_depth;
pub mod skybox;
pub mod ui_overlay;
