// @generated by xtask/shader-bindgen from Slang reflection.
// DO NOT EDIT. Regenerate: `cd xtask && cargo run --bin shader-bindgen -- \
//   ../shaders/reflection ../crates/prism-render/src/shader_bindings`

//! Bindings reflected from `shaders/slang/pt_render.slang`.

#![allow(dead_code, non_snake_case)]

/// Entry point names (for VkPipelineShaderStageCreateInfo).
pub const ENTRY_PT_MAIN: &str = "ptMain"; // stage: COMPUTE

/// Push-constant block size in bytes (reflected).
pub const PUSH_CONSTANT_SIZE: u32 = 0;

// --- descriptor set 0 ---
pub const ACCUM_IMAGE_SET: u32 = 0;
pub const ACCUM_IMAGE_BINDING: u32 = 0; // COMBINED_IMAGE_SAMPLER
pub const SAMPLE_COUNT_SET: u32 = 0;
pub const SAMPLE_COUNT_BINDING: u32 = 1; // COMBINED_IMAGE_SAMPLER
pub const TLAS_SET: u32 = 0;
pub const TLAS_BINDING: u32 = 2; // UNIFORM_BUFFER
pub const VERTEX_DATA_SET: u32 = 0;
pub const VERTEX_DATA_BINDING: u32 = 3; // UNIFORM_BUFFER
pub const INDICES_SET: u32 = 0;
pub const INDICES_BINDING: u32 = 4; // UNIFORM_BUFFER
pub const OUTPUT_IMAGE_SET: u32 = 0;
pub const OUTPUT_IMAGE_BINDING: u32 = 5; // COMBINED_IMAGE_SAMPLER
pub const INSTANCE_META_SET: u32 = 0;
pub const INSTANCE_META_BINDING: u32 = 6; // UNIFORM_BUFFER
pub const MATERIALS_SET: u32 = 0;
pub const MATERIALS_BINDING: u32 = 7; // UNIFORM_BUFFER
pub const PT_LIGHTS_SET: u32 = 0;
pub const PT_LIGHTS_BINDING: u32 = 8; // UNIFORM_BUFFER
pub const PT_EMISSIVE_SET: u32 = 0;
pub const PT_EMISSIVE_BINDING: u32 = 9; // UNIFORM_BUFFER
pub const PREV_RESERVOIR_SET: u32 = 0;
pub const PREV_RESERVOIR_BINDING: u32 = 10; // UNIFORM_BUFFER
pub const CURR_RESERVOIR_SET: u32 = 0;
pub const CURR_RESERVOIR_BINDING: u32 = 11; // UNIFORM_BUFFER

// --- descriptor set 1 ---
pub const GLOBAL_SAMPLERS_SET: u32 = 1;
pub const GLOBAL_SAMPLERS_BINDING: u32 = 0; // UNIFORM_BUFFER
pub const BINDLESS_SRVS_SET: u32 = 1;
pub const BINDLESS_SRVS_BINDING: u32 = 1; // UNIFORM_BUFFER

// --- descriptor set 2 ---
pub const ENV_CUBE_SET: u32 = 2;
pub const ENV_CUBE_BINDING: u32 = 0; // COMBINED_IMAGE_SAMPLER

/// Push-constant struct (auto-generated from Slang `PtPush`).
#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct PtPush {
    /// offset 0, size 64
    pub inv_view_proj: [[f32; 4]; 4],
    /// offset 64, size 16
    pub camera_pos: [f32; 4],
    /// offset 80, size 16
    pub light_dir: [f32; 4],
    /// offset 96, size 16
    pub light_color: [f32; 4],
    /// offset 112, size 16
    pub params: [u32; 4],
    /// offset 128, size 4
    pub ray_max_distance: f32,
    /// offset 132, size 4
    pub max_iterations: u32,
    /// offset 136, size 4
    pub num_lights: u32,
    /// offset 140, size 4
    pub num_emissive: u32,
}
