// @generated by xtask/shader-bindgen from Slang reflection.
// DO NOT EDIT. Regenerate: `cd xtask && cargo run --bin shader-bindgen -- \
//   ../shaders/reflection ../crates/prism-render/src/shader_bindings`

//! Bindings reflected from `shaders/slang/rt_preview.slang`.

#![allow(dead_code, non_snake_case)]

/// Entry point names (for VkPipelineShaderStageCreateInfo).
pub const ENTRY_VERTEX_MAIN: &str = "vertexMain"; // stage: VERTEX
pub const ENTRY_FRAGMENT_MAIN: &str = "fragmentMain"; // stage: FRAGMENT

/// Push-constant block size in bytes (reflected).
pub const PUSH_CONSTANT_SIZE: u32 = 0;

// --- descriptor set 0 ---
pub const GLOBAL_SAMPLERS_SET: u32 = 0;
pub const GLOBAL_SAMPLERS_BINDING: u32 = 0; // UNIFORM_BUFFER
pub const BINDLESS_SRVS_SET: u32 = 0;
pub const BINDLESS_SRVS_BINDING: u32 = 1; // UNIFORM_BUFFER

/// Push-constant struct (auto-generated from Slang `RtPreviewPush`).
#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct RtPreviewPush {
    /// offset 0, size 4
    pub textureHandle: u32,
}
