#![allow(dead_code)]
//! Generated by xtask shader-bindgen from `assets/shaders/reflection/rt_render.json`.
//! 临时占位（本地无 slangc）；CI bindgen 重新生成后内容应与此一致。

pub const ENTRY_VERTEX_MAIN: &str = "vertexMain"; // stage: VERTEX
pub const ENTRY_FRAGMENT_MAIN: &str = "fragmentMain"; // stage: FRAGMENT

#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct RtRenderPush {
    /// offset 0, size 4
    pub pattern: u32,
}
