// @generated by xtask/shader-bindgen from Slang reflection.
// DO NOT EDIT. Regenerate: `cd xtask && cargo run --bin shader-bindgen -- \
//   ../shaders/reflection ../crates/prism-render/src/shader_bindings`

//! Bindings reflected from `shaders/slang/rt_render.slang`.

#![allow(dead_code, non_snake_case)]

/// Entry point names (for VkPipelineShaderStageCreateInfo).
pub const ENTRY_VERTEX_MAIN: &str = "vertexMain"; // stage: VERTEX
pub const ENTRY_FRAGMENT_MAIN: &str = "fragmentMain"; // stage: FRAGMENT

/// Push-constant block size in bytes (reflected).
pub const PUSH_CONSTANT_SIZE: u32 = 0;

/// Push-constant struct (auto-generated from Slang `RtRenderPush`).
#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct RtRenderPush {
    /// offset 0, size 4
    pub pattern: u32,
}
