// @generated by xtask/shader-bindgen from Slang reflection.
// DO NOT EDIT. Regenerate: `cd xtask && cargo run --bin shader-bindgen -- \
//   ../shaders/reflection ../crates/prism-render/src/shader_bindings`

//! Bindings reflected from `shaders/slang/scene_frag.slang`.

#![allow(dead_code, non_snake_case)]


/// Entry point names (for VkPipelineShaderStageCreateInfo).
pub const ENTRY_FRAGMENT_MAIN: &str = "fragmentMain"; // stage: FRAGMENT

/// Push-constant block size in bytes (reflected).
pub const PUSH_CONSTANT_SIZE: u32 = 0;

// --- descriptor set 0 ---
pub const FRAME_SET: u32 = 0;
pub const FRAME_BINDING: u32 = 0; // UNIFORM_BUFFER
pub const MATERIALS_SET: u32 = 0;
pub const MATERIALS_BINDING: u32 = 1; // UNIFORM_BUFFER
pub const POINT_LIGHTS_SET: u32 = 0;
pub const POINT_LIGHTS_BINDING: u32 = 2; // UNIFORM_BUFFER

// --- descriptor set 1 ---
pub const GLOBAL_SAMPLERS_SET: u32 = 1;
pub const GLOBAL_SAMPLERS_BINDING: u32 = 0; // UNIFORM_BUFFER
pub const BINDLESS_SRVS_SET: u32 = 1;
pub const BINDLESS_SRVS_BINDING: u32 = 1; // UNIFORM_BUFFER

// --- descriptor set 2 ---
pub const ENV_CUBE_SET: u32 = 2;
pub const ENV_CUBE_BINDING: u32 = 0; // COMBINED_IMAGE_SAMPLER
pub const IRRADIANCE_CUBE_SET: u32 = 2;
pub const IRRADIANCE_CUBE_BINDING: u32 = 1; // COMBINED_IMAGE_SAMPLER
pub const PREFILTERED_CUBE_SET: u32 = 2;
pub const PREFILTERED_CUBE_BINDING: u32 = 2; // COMBINED_IMAGE_SAMPLER

// --- descriptor set 3 ---
pub const SHADOW_MAP_SET: u32 = 3;
pub const SHADOW_MAP_BINDING: u32 = 0; // COMBINED_IMAGE_SAMPLER
pub const SHADOW_SAMPLER_SET: u32 = 3;
pub const SHADOW_SAMPLER_BINDING: u32 = 1; // COMBINED_IMAGE_SAMPLER

// --- descriptor set 4 ---
pub const AO_TEX_SET: u32 = 4;
pub const AO_TEX_BINDING: u32 = 0; // COMBINED_IMAGE_SAMPLER

// --- descriptor set 5 ---
pub const PROBE_VOLUME_SET: u32 = 5;
pub const PROBE_VOLUME_BINDING: u32 = 0; // COMBINED_IMAGE_SAMPLER
pub const PROBE_INFO_SET: u32 = 5;
pub const PROBE_INFO_BINDING: u32 = 1; // UNIFORM_BUFFER

/// Push-constant struct (auto-generated from Slang `PbrBindlessPush`).
#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct PbrBindlessPush {
    /// offset 0, size 64
    pub model: [[f32; 4]; 4],
    /// offset 64, size 4
    pub material_slot: u32,
    /// offset 68, size 4
    pub env_handle: u32,
    /// offset 72, size 4
    pub albedo_idx: u32,
    /// offset 76, size 4
    pub normal_idx: u32,
    /// offset 80, size 4
    pub debug_flags: u32,
    /// offset 96, size 12
    pub _padding: [u32; 3],
}
