// @generated by xtask/shader-bindgen from Slang reflection.
// DO NOT EDIT. Regenerate: `cd xtask && cargo run --bin shader-bindgen -- \
//   ../shaders/reflection ../crates/prism-render/src/shader_bindings`

//! Bindings reflected from `shaders/slang/shadow_depth.slang`.

#![allow(dead_code, non_snake_case)]


/// Entry point names (for VkPipelineShaderStageCreateInfo).
pub const ENTRY_VERTEX_MAIN: &str = "vertexMain"; // stage: VERTEX
pub const ENTRY_FRAGMENT_MAIN: &str = "fragmentMain"; // stage: FRAGMENT

/// Push-constant block size in bytes (reflected).
pub const PUSH_CONSTANT_SIZE: u32 = 0;

/// Push-constant struct (auto-generated from Slang `ShadowPush`).
#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct ShadowPush {
    /// offset 0, size 64
    pub model: [[f32; 4]; 4],
    /// offset 64, size 64
    pub lightViewProj: [[f32; 4]; 4],
}
