// @generated by xtask/shader-bindgen from Slang reflection.
// DO NOT EDIT. Regenerate: `cd xtask && cargo run --bin shader-bindgen -- \
//   ../shaders/reflection ../crates/prism-render/src/shader_bindings`

//! Bindings reflected from `shaders/slang/ui_overlay.slang`.

#![allow(dead_code, non_snake_case)]

/// Entry point names (for VkPipelineShaderStageCreateInfo).
pub const ENTRY_VERTEX_MAIN: &str = "vertexMain"; // stage: VERTEX
pub const ENTRY_FRAGMENT_MAIN: &str = "fragmentMain"; // stage: FRAGMENT

// --- descriptor set 0 ---
pub const GLYPH_ATLAS_SET: u32 = 0;
pub const GLYPH_ATLAS_BINDING: u32 = 0; // COMBINED_IMAGE_SAMPLER
