[package]
name = "asset-runtime"
version.workspace = true
edition = "2021"
license.workspace = true
description = "Runtime resource loader"

[dependencies]
asset-core = { path = "../asset-core" }
asset-package = { path = "../asset-package" }
serde = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
tracing = "0.1"

[features]
default = ["streaming"]
hot-reload = []
streaming = []

[dev-dependencies]
tempfile = "3"
