[package]
name = "prism-asset-core"
version.workspace = true
edition = "2021"
license.workspace = true
description = "Core types for the resource pipeline: AssetId, Handle, AssetType"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
typetag = { version = "0.2", optional = true }
uuid = { version = "1", features = ["v4"], optional = true }

[features]
asset-data = ["typetag", "uuid"]
default = ["asset-data"]

[dev-dependencies]
bincode = { workspace = true }
