[package]
name = "prism-build-pipeline"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Offline build pipeline: GI bake, asset cooking, etc."

[[bin]]
name = "prism-build-pipeline"
path = "src/main.rs"

[dependencies]
prism-ecs = { path = "../prism-ecs" }
prism-engine = { path = "../prism-engine" }
prism-render = { path = "../prism-render" }
prism-asset = { path = "../prism-asset", default-features = false, features = ["runtime"] }
ash = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
clap = { workspace = true }
rayon = "1"
rand = "0.8"
